=== OscarGitHub102/XML/Structure/SCHEMA/videojuegos.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  
  <xs:element name="ejemplo_videojuegos" type="tipoEjemplo_Videojuegos">

    <xs:complexType name="tipoEjemplo_Videojuegos">
      <xs:sequence>
        <xs:element name="videojuegos" type="tipoVideojuegos"/>
        <xs:element name="usuarios" type="tipoUsuarios"/>
        <xs:element name="prestamos" type="tipoPrestamos"/>
      </xs:sequence>
    </xs:complexType>

    <xs:complexType name="tipoVideojuegos">
      <xs:sequence>
        <xs:element name="videojuego" type="tipoVideojuego" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>

    <xs:complexType name="tipoVideojuego">
      <xs:sequence>
        <xs:element name="titulo" type="xs:string"/>
        <xs:element name="desarrollador" type="xs:string"/>
        <xs:element name="pais_origen" type="xs:string"/>
        <xs:element name="anio" type="xs:integer"/>
        <xs:element name="generos" type="tipoGeneros"/>
        <xs:element name="plataformas" type="tipoPlataformas"/>
      </xs:sequence>
      <xs:attribute name="codigo" type="xs:string" use="required"/>
    </xs:complexType>
    
    <xs:complexType name="tipoGeneros">
      <xs:sequence>
        <xs:element name="genero" type="tipoGenero" maxOccurs="unbounded"/>
     </xs:sequence>
    </xs:complexType>

    <xs:complexType name="tipoGenero">
      <xs:attribute name="nombre" type="xs:string" use="required"/>
    </xs:complexType>
    
    <xs:complexType name="tipoPlataformas">
      <xs:sequence>
        <xs:element name="plataforma" type="tipoPlataforma" maxOccurs="unbounded"/>
     </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="tipoPlataforma">
      <xs:attribute name="maquina" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="tipoUsuarios">
      <xs:sequence>
        <xs:element name="usuario" type="xs:string"/>
        <xs:element name="nombre" type="xs:string"/>
        <xs:element name="tlf" type="xs:integer"/>
      </xs:sequence>
    </xs:complexType>

    <xs:complexType name="tipoPrestamos">
      <xs:sequence>
        <xs:element name="prestamo" type="tipoPrestamo" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>

    <xs:complexType name="tipoPrestamo">
      <xs:sequence>
        <xs:element name="usuario_prestamo" type="xs:string"/>
        <xs:element name="codigo_prestamo" type="xs:string"/>
        <xs:element name="fecha_prestamo" type="xs:date"/>
      </xs:sequence>
    </xs:complexType>
      
  </xs:element>

</xs:schema>

=== OscarGitHub102/XML/Structure/SCHEMA/videojuegos.xml
<?xml version="1.0" encoding="UTF-8"?>
<ejemplo_videojuegos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="videojuegos.xsd">
  <videojuegos>
    <videojuego codigo = "V_1">
      <titulo>The Last of Us II</titulo>
      <desarrollador>Naughty Dog</desarrollador>
      <pais_origen>Estados Unidos</pais_origen>
      <anio>2020</anio>
      <generos>
        <genero nombre="Acción"/>
        <genero nombre="Aventura"/>
        <genero nombre="Terror"/>
      </generos>
      <plataformas>
        <plataforma maquina = "PlayStation"/>
      </plataformas>
    </videojuego>
    <videojuego codigo = "V_2">
      <titulo>Hollow Knight</titulo>
      <desarrollador>Team Cherry</desarrollador>
      <pais_origen>Australia</pais_origen>
      <anio>2017</anio>
      <generos>
        <genero nombre="Plataformas"/>
        <genero nombre="Metroidvania"/>
      </generos>
      <plataformas>
        <plataforma maquina = "PC"/>
        <plataforma maquina = "PlayStation"/>
        <plataforma maquina = "Xbox"/>
        <plataforma maquina = "Switch"/>
      </plataformas>
    </videojuego>
  </videojuegos>
  <usuarios>
    <usuario>jlopez</usuario>
    <nombre>Julia López</nombre>
    <tlf>55512345</tlf>
  </usuarios>
  <prestamos>
    <prestamo>
      <usuario_prestamo>jlopez</usuario_prestamo>
      <codigo_prestamo>V_2</codigo_prestamo>
      <fecha_prestamo>12/09/2019</fecha_prestamo>
    </prestamo>
  </prestamos>
</ejemplo_videojuegos>
