=== OscarGitHub102/XML/Structure/DTD/clase.dtd
<!ELEMENT curso (grupo, horario, equipos)>
<!ELEMENT grupo (nombre, aula)>
<!ELEMENT nombre #PCDATA>
<!ELEMENT aula #CDATA>
<!ELEMENT horario (dia)>
<!ELEMENT dia (nombre, clase)>
<!ATTLIST dia numero CDATA #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT clase (hora, asignatura)>
<!ATTLIST clase orden #CDATA #REQUIRED>
<!ELEMENT hora #PCDATA>
<!ELEMENT asignatura #PCDATA>
<!ELEMENT equipos (equipo)>
<!ELEMENT equipo (num_equipo, ip, mascara, puerta_enlace, alumnos)>
<!ATTLIST equipo id CDATA #REQUIRED>
<!ELEMENT num_equipo #CDATA >
<!ELEMENT ip #PCDATA >
<!ELEMENT mascara #PCDATA >
<!ELEMENT puerta_enlace #PCDATA >
<!ELEMENT alumnos (alumno+) >
<!ELEMENT alumno #PCDATA >
<!ATTLIST alumno alum #CDATA >
<!ELEMENT element (#PCDATA)>

=== OscarGitHub102/XML/Structure/DTD/clase.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE curso SYSTEM "clase.dtd">
<curso>
  <grupo>
    <nombre>1º DAM</nombre>
    <aula>101</aula>
  </grupo>
  <horario>
  <dia número = "1">
    <nombre>Lunes</nombre>
    <clase orden = "1">
      <hora>8:30 - 9:25</hora>
      <asignatura>Entornos de Desarrollo</asignatura>
    </clase>
    <clase orden = "2">
      <hora>9:25 - 10:20</hora>
      <asignatura>Entornos de Desarrollo</asignatura>
    </clase>
    <clase orden = "3">
      <hora>10:20 - 11:15</hora>
      <asignatura>Sistemas Informáticos</asignatura>
    </clase>
    <clase orden = "4">
      <hora>11:15 - 11:40</hora>
      <asignatura>Recreo</asignatura>
    </clase>
    <clase orden = "5">
      <hora>11:40 - 12:35</hora>
      <asignatura>Programación</asignatura>
    </clase>
    <clase orden = "6">
      <hora>12:35 - 13:30</hora>
      <asignatura>Programación</asignatura>
    </clase>
    <clase orden = "7">
      <hora>13:30 - 14:25</hora>
      <asignatura>Programación</asignatura>
    </clase>
  </dia>
  <dia número = "2">
    <nombre>Martes</nombre>
      <clase orden = "1">
        <hora>8:30 - 9:25</hora>
        <asignatura>Bases de Datos</asignatura>
      </clase>
      <clase orden = "2">
        <hora>9:25 - 10:20</hora>
        <asignatura>Bases de Datos</asignatura>
      </clase>
      <clase orden = "3">
        <hora>10:20 - 11:15</hora>
        <asignatura>Formación y Orientación Laboral</asignatura>
      </clase>
      <clase orden = "4">
        <hora>11:15 - 11:40</hora>
        <asignatura>Recreo</asignatura>
      </clase>
      <clase orden = "5">
        <hora>11:40 - 12:35</hora>
        <asignatura>Sistemas Informáticos</asignatura>
      </clase>
      <clase orden = "6">
        <hora>12:35 - 13:30</hora>
        <asignatura>Lenguaje de Marcas</asignatura>
      </clase>
      <clase orden = "7">
        <hora>13:30 - 14:25</hora>
        <asignatura>Lenguaje de Marcas</asignatura>
      </clase>
    </dia>
  <dia número = "3">
    <nombre>Miércoles</nombre>
    <clase orden = "1">
      <hora>8:30 - 9:25</hora>
      <asignatura>Programación</asignatura>
    </clase>
    <clase orden = "2">
      <hora>9:25 - 10:20</hora>
      <asignatura>Programación</asignatura>
    </clase>
    <clase orden = "3">
      <hora>10:20 - 11:15</hora>
      <asignatura>Programación</asignatura>
    </clase>
    <clase orden = "4">
      <hora>11:15 - 11:40</hora>
      <asignatura>Recreo</asignatura>
    </clase>
    <clase orden = "5">
      <hora>11:40 - 12:35</hora>
      <asignatura>Formación y Orientación Laboral</asignatura>
    </clase>
    <clase orden = "6">
      <hora>12:35 - 13:30</hora>
      <asignatura>Bases de Datos</asignatura>
    </clase>
    <clase orden = "7">
      <hora>13:30 - 14:25</hora>
      <asignatura>Entornos de Desarrollo</asignatura>
    </clase>
  </dia>
  <dia número = "4">
  <nombre>Jueves</nombre>
    <clase orden = "1">
      <hora>8:30 - 9:25</hora>
      <asignatura>Lenguaje de Marcas</asignatura>
    </clase>
    <clase orden = "2">
      <hora>9:25 - 10:20</hora>
      <asignatura>Lenguaje de Marcas</asignatura>
    </clase>
    <clase orden = "3">
      <hora>10:20 - 11:15</hora>
      <asignatura>Sistemas Informáticos</asignatura>
    </clase>
    <clase orden = "4">
      <hora>11:15 - 11:40</hora>
      <asignatura>Recreo</asignatura>
    </clase>
    <clase orden = "5">
      <hora>11:40 - 12:35</hora>
      <asignatura>Bases de Datos</asignatura>
    </clase>
    <clase orden = "6">
      <hora>12:35 - 13:30</hora>
      <asignatura>Bases de Datos</asignatura>
    </clase>
    <clase orden = "7">
      <hora>13:30 - 14:25</hora>
      <asignatura>Bases de Datos</asignatura>
    </clase>
  </dia>
  <dia número = "5">
    <nombre>Viernes</nombre>
    <clase orden = "1">
      <hora>8:30 - 9:25</hora>
      <asignatura>Sistemas Informáticos</asignatura>
    </clase>
    <clase orden = "2">
      <hora>9:25 - 10:20</hora>
      <asignatura>Sistemas Informáticos</asignatura>
    </clase>
    <clase orden = "3">
      <hora>10:20 - 11:15</hora>
      <asignatura>Sistemas Informáticos</asignatura>
    </clase>
    <clase orden = "4">
      <hora>11:15 - 11:40</hora>
      <asignatura>Recreo</asignatura>
    </clase>
    <clase orden = "5">
      <hora>11:40 - 12:35</hora>
      <asignatura>Formación y Orientación Laboral</asignatura>
    </clase>
    <clase orden = "6">
      <hora>12:35 - 13:30</hora>
      <asignatura>Programación</asignatura>
    </clase>
    <clase orden = "7">
      <hora>13:30 - 14:25</hora>
      <asignatura>Programación</asignatura>
    </clase>
  </dia>
  </horario>
  <equipos>
    <equipo id = "1">
      <num_equipo>01</num_equipo>
      <ip>192.168.0.01</ip>
      <mascara>255.255.255.0</mascara>
      <puerta_enlace>255.255.0.254</puerta_enlace>
      <alumnos>
        <alumno alum = "1">Paco Fernández</alumno>
        <alumno alum = "2">Alicia Pérez</alumno>
      </alumnos>
    </equipo>
    <equipo id = "2">
      <num_equipo>02</num_equipo>
      <ip>192.168.0.02</ip>
      <mascara>255.255.255.0</mascara>
      <puerta_enlace>255.255.0.254</puerta_enlace>
      <alumnos>
        <alumno alum = "1">Álvaro Ortega</alumno>
        <alumno alum = "2">Juan Rodríguez</alumno>
      </alumnos>
    </equipo>
    <equipo id = "3">
      <num_equipo>03</num_equipo>
      <ip>192.168.0.03</ip>
      <mascara>255.255.255.0</mascara>
      <puerta_enlace>255.255.0.254</puerta_enlace>
      <alumnos>
        <alumno alum = "1">María García</alumno>
        <alumno alum = "2">Irene Herránz</alumno>
      </alumnos>
    </equipo>
  </equipos>
</curso>
