=== OscarGitHub102/XML/Structure/DTD/peliculas.dtd
<!ELEMENT peliculas (pelicula+)>
<!ELEMENT pelicula (titulo, titori, nacionalidades, idiomas, anio.produccion, director, interpretes)>
<!ATTLIST pelicula orden CDATA #REQUIRED>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT tit.ori (#PCDATA)>
<!ELEMENT nacionalidades (nacionalidad+)>
<!ELEMENT nacionalidad (#PCDATA)>
<!ATTLIST nacionalidad nacion CDATA #REQUIRED>
<!ELEMENT idiomas (idioma+)>
<!ELEMENT idioma (#PCDATA)>
<!ELEMENT anio.produccion (#CDATA)>
<!ELEMENT directores (director+)>
<!ELEMENT director (#PCDATA)>
<!ELEMENT interpretes (interprete+)>
<!ELEMENT interprete (#PCDATA)>
<!ATTLIST interprete numero CDATA #REQUIRED>

=== OscarGitHub102/XML/Structure/DTD/peliculas.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE peliculas SYSTEM "peliculas.dtd">
<peliculas>
  <pelicula orden = "1">
    <titulo>Interestelar</titulo>
    <tit.ori>Interstellar</tit.ori>
    <nacionalidades>
        <nacionalidad nacion = "1">Estados Unidos</nacionalidad>
        <nacionalidad nacion = "2">Reino Unido</nacionalidad>
        <nacionalidad nacion = "3">Canadá</nacionalidad>
    </nacionalidades>
    <idiomas>
      <idioma>Inglés</idioma>
    </idiomas>
    <anio.produccion>2014</anio.produccion>
    <directores>
     <director>Christopher Nolan</director>
    </directores>
    <interpretes>
      <interprete numero = "1">Matthew McConaughey</interprete>
      <interprete numero = "2">Anne Hathaway</interprete>
      <interprete numero = "3">Jessica Chastain</interprete>
      <interprete numero = "4">Bill Irwin</interprete>
    </interpretes>
  </pelicula>
  <pelicula orden = "2">
    <titulo>Soy leyenda</titulo>
    <tit.ori>I am a legend</tit.ori>
    <nacionalidades>
      <nacionalidad>Estados Unidos</nacionalidad>
    </nacionalidades>
    <idiomas>
      <idioma>Inglés</idioma>
    </idiomas>
    <anio.produccion>2007</anio.produccion>
    <directores>
      <director>Francis Lawrence</director>
    </directores>
    <interpretes>
        <interprete numero = "1">Will Smith</interprete>
        <interprete numero = "2">Alice Braga</interprete>
        <interprete numero = "3">Dash Mihok</interprete>
    </interpretes>
  </pelicula>
  <pelicula orden = "3">
    <titulo>Lo imposible</titulo>
    <tit.ori>The Impossible</tit.ori>
  <nacionalidades>
      <nacionalidad>España</nacionalidad>
    </nacionalidades>
    <idiomas>
        <idioma idio = "1">Inglés</idioma>
        <idioma idio = "2">Tailandés</idioma>
    </idiomas>
    <anio.produccion>2012</anio.produccion>
    <directores>
      <director>Juan Antonio Bayona</director>
    </directores>
    <interpretes>
        <interprete numero = "1">Naomi Watts</interprete>
        <interprete numero = "2">Ewan McGregor</interprete>
        <interprete numero = "3">Tom Hollland</interprete>
        <interprete numero = "4">Samuel Joslin</interprete>
    </interpretes>
  </pelicula>
  <pelicula orden = "4">
    <titulo>Intocable</titulo>
    <tit.ori>Intouchables</tit.ori>
    <nacionalidades>
      <nacionalidad>Francia</nacionalidad>
    </nacionalidades>
    <idiomas>
      <idioma>Francés</idioma>
    </idiomas>
    <anio.produccion>2011</anio.produccion>
    <directores>
        <director direc = "1">Olivier Nakache</director>
        <director direc = "2">Éric Toledano</director>
    </directores>  
    <interpretes>
        <interprete numero = "1">François Cluzet</interprete>
        <interprete numero = "2">Omar Sy</interprete>
    </interpretes>
  </pelicula>
  <pelicula orden = "5">
    <titulo>El lobo de Wall Street</titulo>
    <tit.ori>The Wolf of Wall Street</tit.ori>
    <nacionalidades>
      <nacionalidad>Reino Unido</nacionalidad>
    </nacionalidades>
    <idiomas>
      <idioma>Inglés</idioma>
    </idiomas>
    <anio.produccion>2013</anio.produccion>
    <directores>
      <director>Martin Scorsese</director>
    </directores>
    <interpretes>
        <interprete numero = "1">Leonardo DiCaprio</interprete>
        <interprete numero = "2">Jonah Hill</interprete>
        <interprete numero = "3">Margot Robbie</interprete>
    </interpretes>
  </pelicula>
</peliculas>
